# Generated by Django 5.2.7 on 2025-11-06 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authapi', '0003_doctor_unique_doctor_phone_and_more'),
        ('appointments', '0002_remove_appointment_appointment_appoint_5be6a4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('patient_doctor', 'Patient-Doctor Chat'), ('doctor_doctor', 'Doctor-Doctor Chat'), ('group', 'Disease Support Group')], db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disease_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='appointments.appointment')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_connection', to='chat_room.chatroom')),
                ('from_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='Authapi.doctor')),
                ('to_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='Authapi.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_diagnosed', models.BooleanField(default=False, help_text='Verified diagnosis for this disease')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat_room.chatroom')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='Authapi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_room.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'is_active'], name='chat_room_c_room_ty_84a8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorconnection',
            index=models.Index(fields=['to_doctor', 'status'], name='chat_room_d_to_doct_ac0c69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorconnection',
            unique_together={('from_doctor', 'to_doctor')},
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['patient', 'group_room'], name='chat_room_g_patient_af6c37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('patient', 'group_room')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='chat_room_m_room_id_fd4efd_idx'),
        ),
    ]
