# Generated by Django 5.2.7 on 2025-11-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='disease_name',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('patient_doctor', 'Patient-Doctor Chat'), ('doctor_doctor', 'Doctor-Doctor Chat')], db_index=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
