# Generated by Django 5.2.7 on 2025-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_type',
            field=models.CharField(blank=True, help_text='verification or reset', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval for doctor account'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Medical Council Registration Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='Chronic diseases (comma separated)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_email',
            field=models.EmailField(blank=True, help_text='Emergency contact email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_medical_history',
            field=models.TextField(blank=True, help_text='Family medical history', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_insurance',
            field=models.BooleanField(default=False, help_text='Has medical insurance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='known_allergies',
            field=models.TextField(blank=True, help_text='Known allergies (comma separated)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='previous_surgeries',
            field=models.TextField(blank=True, help_text='Previous surgeries history', null=True),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization'], name='Authapi_doc_special_7e2b76_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['city'], name='Authapi_pat_city_71f533_idx'),
        ),
    ]
