version: '3.8'

services:
  db:
    image: postgres:15
    container_name: medtrax-db
    restart: always
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medtraxdata}
      POSTGRES_USER: ${POSTGRES_USER:-medtraxadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Medtrax2025}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medtraxadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: medtrax-redis
    env_file:
      - .env.docker
    command: ["redis-server"]
    restart: always
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medtrax-web
    environment:
      - RUNNING_IN_DOCKER=true 
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'Database is ready!' &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 medtrax.asgi:application
      "
    env_file:
      - .env.docker
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medtrax-celery
    command: >
      sh -c "
        echo 'Waiting for web to be ready...' &&
        sleep 15 &&
        celery -A medtrax worker --loglevel=info
      "
    env_file:
      - .env.docker
    volumes:
      - media_volume:/app/media
    depends_on:
      - redis
      - db
      - web
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medtrax-celery-beat
    command: >
      sh -c "
        echo 'Waiting for web to be ready...' &&
        sleep 20 &&
        celery -A medtrax beat --loglevel=info
      "
    env_file:
      - .env.docker
    depends_on:
      - redis
      - db
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: