# Generated by Django 5.2.7 on 2025-10-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authapi', '0003_doctor_unique_doctor_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of appointment')),
                ('appointment_time', models.TimeField(help_text='Time slot for appointment')),
                ('duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('reason_for_visit', models.TextField(help_text='Chief complaint/reason for visit')),
                ('symptoms', models.TextField(blank=True, help_text='Current symptoms', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's notes after appointment", null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='Authapi.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Authapi.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_8037cd_idx'), models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4d4b79_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'), models.Index(fields=['appointment_date'], name='appointment_appoint_5be6a4_idx')],
                'unique_together': {('doctor', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
