# Generated by Django 5.2.7 on 2025-11-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapi', '0003_doctor_unique_doctor_phone_and_more'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_appoint_5be6a4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text="Doctor's notes about the appointment", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Authapi.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason_for_visit',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='symptoms',
        ),
    ]
